# Generated by Django 4.2.10 on 2025-01-18 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('skills', models.CharField(blank=True, choices=[('web_dev', 'Web Development'), ('graphic_design', 'Graphic Design'), ('content_writing', 'Content Writing'), ('seo', 'SEO'), ('digital_marketing', 'Digital Marketing'), ('data_analysis', 'Data Analysis'), ('app_dev', 'App Development'), ('project_mgmt', 'Project Management')], max_length=50, null=True)),
                ('experience', models.PositiveIntegerField(default=0, help_text='Years of experience in freelancing or related work.')),
                ('location', models.CharField(blank=True, help_text='City, State, or Country of the freelancer.', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
