# Generated by Django 4.2.10 on 2025-02-02 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_bio_profile_introduction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('requested', 'Requested'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('receving_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receving_user', to=settings.AUTH_USER_MODEL)),
                ('sending_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
