# Generated by Django 4.2.10 on 2025-02-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='job',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='app1.job'),
            preserve_default=False,
        ),
    ]
