# Generated by Django 4.2.10 on 2025-02-16 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_applications_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='working_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='working_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
