# Generated by Django 4.2.10 on 2025-03-17 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_job_working_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_file', models.FileField(upload_to='job_outputs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_outputs', to='app1.job')),
            ],
        ),
    ]
