# Generated by Django 4.2.10 on 2025-05-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payout_request',
            field=models.BooleanField(default=False),
        ),
    ]
